using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LcdModCodeGenerator;

[Generator]
public sealed class ConfigKinds : IIncrementalGenerator
{
    static readonly DiagnosticDescriptor DuplicateIdWarning = new(
        id: "LCDMOD002",
        title: "Duplicate config Id",
        messageFormat: "config Id '{0}' is used by multiple classes: {1}",
        category: "LcdModCodeGenerator",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    static readonly DiagnosticDescriptor UseAppConfigWarning = new(
        id: "LCDMOD003",
        title: "Use AppConfig",
        messageFormat: "Use the resolved AppConfig instead of Config in '{0}'",
        category: "LcdModCodeGenerator",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static spc =>
        {
            spc.AddSource("IScreenConfig.g.cs", @"// <auto-generated/>
namespace Generated
{
    public interface IScreenConfig
    {
        int Id { get; }
    }
}");
        });

        var compilationProvider = context.CompilationProvider;
        context.RegisterSourceOutput(compilationProvider, static (spc, compilation) =>
        {
            var entries = GetEntries(compilation, spc);
            spc.AddSource("ConfigKind.g.cs", BuildEnumSource(entries));
            spc.AddSource("IConfigGenerator.g.cs", BuildConfigGeneratorSource(entries));
            var appConfigs = GetAppConfigs(compilation, entries);
            var appConfigSource = BuildAppConfigsSource(appConfigs);
            if (appConfigSource != null)
                spc.AddSource("AppConfigs.g.cs", appConfigSource);
            ReportConfigPropertyUsages(compilation, appConfigs, spc);
        });
    }

    static List<(string Name, int Id, INamedTypeSymbol Type)> GetEntries(Compilation compilation, SourceProductionContext spc)
    {
        var interfaceSymbol = compilation.GetTypeByMetadataName("Generated.IScreenConfig");
        if (interfaceSymbol == null)
            return null;

        var entries = new List<(string Name, int Id, INamedTypeSymbol Type)>();
        CollectEntries(compilation.Assembly.GlobalNamespace, interfaceSymbol, entries);

        if (entries.Count == 0)
            return null;

        ReportDuplicateIds(entries, spc);
        return entries
            .GroupBy(e => e.Name)
            .Select(g => g.OrderBy(e => e.Id).First())
            .OrderBy(e => e.Id)
            .ThenBy(e => e.Name)
            .ToList();
    }

    static string BuildEnumSource(List<(string Name, int Id, INamedTypeSymbol Type)> distinct)
    {
        if (distinct == null || distinct.Count == 0)
            return GetFallbackSource();
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public enum ConfigKind");
        sb.AppendLine("    {");
        for (var i = 0; i < distinct.Count; i++)
        {
            var entry = distinct[i];
            var separator = i == distinct.Count - 1 ? "" : ",";
            sb.AppendLine($"        {entry.Name} = {entry.Id}{separator}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
    
    static string BuildConfigGeneratorSource(List<(string Name, int Id, INamedTypeSymbol Type)> entries)
    {
        var hasBaseType = TryGetBaseType(entries, out var baseType);
        var returnTypeName = hasBaseType ? GetTypeName(baseType) : "IScreenConfig";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        foreach (var @namespace in GetRequiredNamespaces(entries))
            sb.AppendLine($"using {@namespace};");
        
        if (!hasBaseType)
            sb.AppendLine("using System;");
        
        sb.AppendLine("using Sandbox.ModAPI;");

        sb.AppendLine();
        sb.AppendLine("namespace Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public interface IConfigGenerator");
        sb.AppendLine("    {");
        sb.AppendLine($"        {returnTypeName} GenerateConfig(ConfigKind requestedConfigKind);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public sealed class ConfigGenerator : IConfigGenerator");
        sb.AppendLine("    {");
        BuildConfigGeneratorGenerateConfig(entries, sb, returnTypeName, hasBaseType);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)> GetAppConfigs(
        Compilation compilation,
        List<(string Name, int Id, INamedTypeSymbol Type)> entries)
    {
        if (entries == null || entries.Count == 0)
            return null;

        var surfaceScriptBase = compilation.GetTypeByMetadataName("Graph.Apps.Abstract.SurfaceScriptBase");
        if (surfaceScriptBase == null)
            return null;

        var configByKind = entries
            .GroupBy(e => e.Name)
            .ToDictionary(g => g.Key, g => g.OrderBy(e => e.Id).First().Type);
        var appConfigs = new List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)>();

        CollectAppConfigs(compilation.Assembly.GlobalNamespace, surfaceScriptBase, configByKind, appConfigs);
        return appConfigs;
    }

    static string BuildAppConfigsSource(List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)> appConfigs)
    {
        if (appConfigs == null || appConfigs.Count == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        foreach (var group in appConfigs
            .OrderBy(e => e.AppType.ContainingNamespace.ToDisplayString())
            .ThenBy(e => e.AppType.Name)
            .GroupBy(e => e.AppType.ContainingNamespace.ToDisplayString()))
        {
            sb.AppendLine();
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var appConfig in group)
                AddAppConfig(sb, appConfig.AppType, appConfig.ConfigType);

            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void ReportConfigPropertyUsages(
        Compilation compilation,
        List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)> appConfigs,
        SourceProductionContext spc)
    {
        if (appConfigs == null || appConfigs.Count == 0)
            return;

        var surfaceScriptBase = compilation.GetTypeByMetadataName("Graph.Apps.Abstract.SurfaceScriptBase");
        var configProperty = surfaceScriptBase?.GetMembers("Config").OfType<IPropertySymbol>().FirstOrDefault();
        if (configProperty == null)
            return;

        foreach (var appType in appConfigs.Select(e => e.AppType))
        {
            foreach (var syntaxRef in appType.DeclaringSyntaxReferences)
            {
                if (syntaxRef.GetSyntax() is not ClassDeclarationSyntax classSyntax)
                    continue;

                var model = compilation.GetSemanticModel(classSyntax.SyntaxTree);
                foreach (var identifier in classSyntax.DescendantNodes().OfType<IdentifierNameSyntax>())
                {
                    if (identifier.Identifier.ValueText != "Config" || !IsImplicitOrThisConfigReference(identifier))
                        continue;

                    var symbol = model.GetSymbolInfo(identifier).Symbol as IPropertySymbol;
                    if (symbol == null || !SymbolEqualityComparer.Default.Equals(symbol.OriginalDefinition, configProperty))
                        continue;

                    spc.ReportDiagnostic(Diagnostic.Create(
                        UseAppConfigWarning,
                        identifier.GetLocation(),
                        appType.Name));
                }
            }
        }
    }

    static bool IsImplicitOrThisConfigReference(IdentifierNameSyntax identifier)
    {
        if (identifier.Parent is MemberAccessExpressionSyntax memberAccess)
            return memberAccess.Name == identifier && memberAccess.Expression is ThisExpressionSyntax;

        return true;
    }

    static void AddAppConfig(StringBuilder sb, INamedTypeSymbol appType, INamedTypeSymbol configType)
    {
        var accessibility = GetAccessibility(appType);
        var typeName = GetPartialTypeName(appType);
        var configTypeName = GetFullyQualifiedTypeName(configType);

        sb.AppendLine($"    {accessibility} partial class {typeName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private {configTypeName} AppConfig => ({configTypeName})Config;");
        sb.AppendLine("    }");
    }

    static void CollectAppConfigs(
        INamespaceSymbol ns,
        INamedTypeSymbol surfaceScriptBase,
        Dictionary<string, INamedTypeSymbol> configByKind,
        List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)> appConfigs)
    {
        foreach (var type in ns.GetTypeMembers())
            CollectAppConfigsInType(type, surfaceScriptBase, configByKind, appConfigs);

        foreach (var childNs in ns.GetNamespaceMembers())
            CollectAppConfigs(childNs, surfaceScriptBase, configByKind, appConfigs);
    }

    static void CollectAppConfigsInType(
        INamedTypeSymbol type,
        INamedTypeSymbol surfaceScriptBase,
        Dictionary<string, INamedTypeSymbol> configByKind,
        List<(INamedTypeSymbol AppType, INamedTypeSymbol ConfigType)> appConfigs)
    {
        if (type.TypeKind == TypeKind.Class
            && InheritsFrom(type, surfaceScriptBase)
            && IsPartial(type)
            && TryGetConfigKindName(type, out var configKindName)
            && configByKind.TryGetValue(configKindName, out var configType))
        {
            appConfigs.Add((type, configType));
        }

        foreach (var nested in type.GetTypeMembers())
            CollectAppConfigsInType(nested, surfaceScriptBase, configByKind, appConfigs);
    }

    static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var current = type.BaseType; current != null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
        }

        return false;
    }

    static bool IsPartial(INamedTypeSymbol type) =>
        type.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));

    static bool TryGetConfigKindName(INamedTypeSymbol type, out string configKindName)
    {
        configKindName = null;
        var configKind = FindConfigKind(type);

        var syntaxRef = configKind?.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef?.GetSyntax() is not PropertyDeclarationSyntax propSyntax)
            return false;

        return TryReadConfigKindName(propSyntax.ExpressionBody?.Expression, out configKindName);
    }

    static IPropertySymbol FindConfigKind(INamedTypeSymbol type)
    {
        for (var current = type; current != null; current = current.BaseType)
        {
            var configKind = current.GetMembers("ConfigKind")
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.IsOverride);

            if (configKind != null)
                return configKind;
        }

        return null;
    }

    static bool TryReadConfigKindName(ExpressionSyntax expression, out string configKindName)
    {
        configKindName = null;
        if (expression is MemberAccessExpressionSyntax memberAccess)
        {
            configKindName = memberAccess.Name.Identifier.ValueText;
            return !string.IsNullOrEmpty(configKindName);
        }

        if (expression is IdentifierNameSyntax identifier)
        {
            configKindName = identifier.Identifier.ValueText;
            return !string.IsNullOrEmpty(configKindName);
        }

        return false;
    }

    static string GetAccessibility(INamedTypeSymbol type)
    {
        switch (type.DeclaredAccessibility)
        {
            case Accessibility.Public:
                return "public";
            case Accessibility.Internal:
                return "internal";
            case Accessibility.Private:
                return "private";
            case Accessibility.Protected:
                return "protected";
            case Accessibility.ProtectedAndInternal:
                return "private protected";
            case Accessibility.ProtectedOrInternal:
                return "protected internal";
            default:
                return "internal";
        }
    }

    static string GetPartialTypeName(INamedTypeSymbol type)
    {
        if (type.TypeParameters.Length == 0)
            return type.Name;

        return type.Name + "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";
    }

    static string GetFullyQualifiedTypeName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    static void BuildConfigGeneratorGenerateConfig(List<(string Name, int Id, INamedTypeSymbol Type)> entries, StringBuilder sb, string returnTypeName, bool hasBaseType)
    {
        sb.AppendLine($"        public {returnTypeName} GenerateConfig(ConfigKind requestedConfigKind)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (requestedConfigKind)");
        sb.AppendLine("            {");

        if (entries != null)
        {
            foreach (var entry in entries)
            {
                var typeName = GetTypeName(entry.Type);
                sb.AppendLine($"                case ConfigKind.{entry.Name}:");
                sb.AppendLine($"                    return new {typeName}();");
            }
        }

        sb.AppendLine("                default:");
        sb.AppendLine(hasBaseType
            ? $"                    return new {returnTypeName}();"
            : "                    throw new NotSupportedException(\"No Base config type was found. Add an IScreenConfig implementation with Id = 0.\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    static bool TryGetBaseType(List<(string Name, int Id, INamedTypeSymbol Type)> entries, out INamedTypeSymbol baseType)
    {
        baseType = entries?
            .Where(e => e.Name == "Base")
            .OrderBy(e => e.Id)
            .Select(e => e.Type)
            .FirstOrDefault();

        return baseType != null;
    }

    static IEnumerable<string> GetRequiredNamespaces(List<(string Name, int Id, INamedTypeSymbol Type)> entries)
    {
        if (entries == null)
            yield break;

        foreach (var @namespace in entries
            .Select(e => e.Type.ContainingNamespace)
            .Where(ns => ns != null && !ns.IsGlobalNamespace)
            .Select(ns => ns.ToDisplayString())
            .Where(ns => ns != "Generated")
            .Distinct()
            .OrderBy(ns => ns))
        {
            yield return @namespace;
        }
    }

    static string GetTypeName(INamedTypeSymbol type) =>
        type.ToDisplayString(new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters));

    static void CollectEntries(INamespaceSymbol ns, INamedTypeSymbol iface, List<(string Name, int Id, INamedTypeSymbol Type)> entries)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            if (type.TypeKind == TypeKind.Class && !type.IsAbstract && Implements(type, iface))
            {
                var declaredId = type.GetMembers("Id")
                    .OfType<IPropertySymbol>()
                    .FirstOrDefault(p => SymbolEqualityComparer.Default.Equals(p.ContainingType, type));

                if (declaredId?.GetMethod != null && TryGetIntValue(declaredId, out var id))
                    entries.Add((GetEnumName(type.Name, id), id, type));
            }

            foreach (var nested in type.GetTypeMembers())
                CollectEntriesInType(nested, iface, entries);
        }

        foreach (var childNs in ns.GetNamespaceMembers())
            CollectEntries(childNs, iface, entries);
    }

    static void CollectEntriesInType(INamedTypeSymbol type, INamedTypeSymbol iface, List<(string Name, int Id, INamedTypeSymbol Type)> entries)
    {
        if (type.TypeKind == TypeKind.Class && !type.IsAbstract && Implements(type, iface))
        {
            var declaredId = type.GetMembers("Id")
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => SymbolEqualityComparer.Default.Equals(p.ContainingType, type));

            if (declaredId?.GetMethod != null && TryGetIntValue(declaredId, out var id))
                entries.Add((GetEnumName(type.Name, id), id, type));
        }

        foreach (var nested in type.GetTypeMembers())
            CollectEntriesInType(nested, iface, entries);
    }

    static bool Implements(INamedTypeSymbol type, INamedTypeSymbol iface) =>
        type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iface));

    static bool TryGetIntValue(IPropertySymbol property, out int value)
    {
        value = default;
        if (property.Type.SpecialType != SpecialType.System_Int32)
            return false;

        var syntaxRef = property.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef?.GetSyntax() is not PropertyDeclarationSyntax propSyntax)
            return false;

        if (TryReadLiteral(propSyntax.ExpressionBody?.Expression, out value))
            return true;

        var getter = propSyntax.AccessorList?.Accessors.FirstOrDefault(a => a.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.GetAccessorDeclaration));
        if (getter == null)
            return false;

        if (TryReadLiteral(getter.ExpressionBody?.Expression, out value))
            return true;

        if (getter.Body?.Statements.Count == 1
            && getter.Body.Statements[0] is ReturnStatementSyntax returnStatement
            && TryReadLiteral(returnStatement.Expression, out value))
            return true;

        return false;
    }

    static void ReportDuplicateIds(List<(string Name, int Id, INamedTypeSymbol Type)> entries, SourceProductionContext spc)
    {
        var duplicates = entries
            .GroupBy(e => e.Id)
            .Where(g => g.Count() > 1);

        foreach (var duplicate in duplicates)
        {
            var sorted = duplicate.OrderBy(d => d.Type.Name).ToArray();
            var typeList = string.Join(", ", sorted.Select(d => d.Type.ToDisplayString()));
            foreach (var entry in sorted)
            {
                var location = entry.Type.Locations.FirstOrDefault() ?? Location.None;
                spc.ReportDiagnostic(Diagnostic.Create(DuplicateIdWarning, location, duplicate.Key, typeList));
            }
        }
    }

    static bool TryReadLiteral(ExpressionSyntax expression, out int value)
    {
        value = default;
        if (expression == null)
            return false;

        if (expression is LiteralExpressionSyntax literal &&
            literal.Token.Value is int literalValue)
        {
            value = literalValue;
            return true;
        }

        if (expression is PrefixUnaryExpressionSyntax unary &&
            unary.Operand is LiteralExpressionSyntax unaryLiteral &&
            unaryLiteral.Token.Value is int unaryValue)
        {
            value = unary.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.UnaryMinusExpression) ? -unaryValue : unaryValue;
            return true;
        }

        return false;
    }

    static string GetEnumName(string typeName, int id)
    {
        if (id == 0)
            return "Base";
        if (typeName.StartsWith("ScreenConfig"))
            return typeName.Substring("ScreenConfig".Length);
        return typeName;
    }

    static string GetFallbackSource() => @"// <auto-generated/>
namespace Generated
{
    public enum ConfigKind
    {
        Base = 0
    }
}";
}
